---
- name: Instalacion de apache en servidores W16DC
  hosts: student1-win1
  tasks:
    - name: Download MSI Apache installer
      win_get_url:
        url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
        dest: C:\repositorios\httpd-2.2.25-win32-x86-no_ssl.msi
