---
- name: add user
  hosts: student1-win1
  gather_facts: false
  
  tasks:
    - name: crear usuario para enfemeros
      win_user:
        name: hospitalimss
        password: "123abc."
        state: present
